version: '3'

vars:
  TAGS:
    default: ''
    sh: |
      if [ -n "$TAGS" ]; then
        echo "$TAGS"
      else
        echo "Please provide tags (comma-separated):"
        read input
        echo "$input"
      fi

tasks:
  list:
    desc: List all available ansible tasks
    cmds:
    - ansible-playbook nas.yml --list-tasks

  deploy:
    desc: Deploy full media server configuration
    cmds:
    - ansible-playbook nas.yml -b -K

  check:
    desc: Dry-run full deployment with diff
    cmds:
    - ansible-playbook nas.yml -b -K --check --diff

  deploy:hus:
    desc: Deploy to hus host group
    cmds:
    - ansible-playbook nas.yml -b -K -l hus

  check:hus:
    desc: Dry-run hus deployment with diff
    cmds:
    - ansible-playbook nas.yml -b -K -l hus --check --diff

  deploy:hms:
    desc: Deploy to hms host group
    cmds:
    - ansible-playbook nas.yml -b -K -l hms

  check:hms:
    desc: Dry-run hms deployment with diff
    cmds:
    - ansible-playbook nas.yml -b -K -l hms --check --diff

  deploy:tags:
    desc: "Deploy with specific tags"
    vars:
      TAGS: '{{.TAGS}}'
    cmds:
      - |
        if [ -z "{{.TAGS}}" ]; then
          echo "No tags provided. Please provide tags (comma-separated):"
          read input
          TAGS=$input
        else
          TAGS="{{.TAGS}}"
        fi
        echo "Deploying with tags: $TAGS"


        ansible-playbook nas.yml -b -K --tags="$TAGS"

  check:tags:
    desc: "Check with specific tags"
    vars:
      TAGS: '{{.TAGS}}'
    cmds:
      - |
        if [ -z "{{.TAGS}}" ]; then
          echo "No tags provided. Please provide tags (comma-separated):"
          read input
          TAGS=$input
        else
          TAGS="{{.TAGS}}"
        fi
        echo "Checking with tags: $TAGS"


        ansible-playbook nas.yml -b -K --tags="$TAGS" --check --diff

  default:
    cmds:
    - task --list
