---
paperless_ngx_enabled: false
paperless_ngx_available_externally: false

# directories
paperless_ngx_config_directory: "{{ docker_home }}/paperless_ngx"
paperless_ngx_files_directory: "{{ documents_root }}/paperless_ngx"

paperless_ngx_postgres_directory: "{{ paperless_ngx_config_directory }}/postgres"
paperless_ngx_data_directory: "{{ paperless_ngx_config_directory }}/data"
paperless_ngx_export_directory: "{{ paperless_ngx_config_directory }}/export"
paperless_ngx_media_directory: "{{ paperless_ngx_files_directory }}/media"
paperless_ngx_consume_directory: "{{ paperless_ngx_files_directory }}/consume"

# network
paperless_ngx_port: "16923"
paperless_ngx_hostname: "paperless_ngx"
paperless_ngx_network_name: "paperless_ngx"

# postgres
paperless_ngx_postgres_db: "paperless"
paperless_ngx_postgres_user: "paperless"
paperless_ngx_postgres_password: "paperless"

# container names

paperless_ngx_redis_container_name: "paperless-ngx-redis"
paperless_ngx_redis_image_name: "redis"
paperless_ngx_redis_image_version: "6.0"

paperless_ngx_db_container_name: "paperless-ngx-db"
paperless_ngx_db_image_name: "postgres"
paperless_ngx_db_image_version: "13"

paperless_ngx_uiserver_container_name: "paperless-ngx-uiserver"
paperless_ngx_uiserver_image_name: "ghcr.io/paperless-ngx/paperless-ngx"
paperless_ngx_uiserver_image_version: "latest"

# uid/guid
paperless_ngx_user_id: "1000"
paperless_ngx_group_id: "1000"

# settings
paperless_ngx_languages: "deu eng"

# specs
paperless_ngx_ui_memory: 1g
paperless_ngx_postgres_memory: 1g
paperless_ngx_redis_memory: 1g
