---
- name: Include variables
  include_vars:
    file: vars/main.yml
    name: paperless_ngx_volumes

- name: Deploy paperless-ngx with docker-compose
  block:
  - name: Create paperless_ngx directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "/opt/paperless_ngx/"
    - "{{ paperless_ngx_config_directory }}"
    - "{{ paperless_ngx_files_directory }}"
    - "{{ paperless_ngx_postgres_directory }}"
    - "{{ paperless_ngx_data_directory }}"
    - "{{ paperless_ngx_export_directory }}"
    - "{{ paperless_ngx_media_directory }}"
    - "{{ paperless_ngx_consume_directory }}"
  - name: Deploy Paperless_NGX Docker Compose file
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: /opt/paperless_ngx/docker-compose.yml
    tags:
    - paperless_ngx
    - docker
  - name: Start Paperless_NGX container
    community.docker.docker_compose_v2:
      project_src: /opt/paperless_ngx/
      state: present
  when: paperless_ngx_enabled
  tags:
  - paperless_ngx
  - docker

- name: Remove paperless_ngx
  block:
  - name: Check if paperless_ngx project directory exists
    ansible.builtin.stat:
      path: /opt/paperless_ngx/docker-compose.yml
    register: paperless_compose_file
  - name: Stop Paperless_NGX container
    community.docker.docker_compose_v2:
      project_src: /opt/paperless_ngx/
      state: absent
      remove_volumes: true
    when: paperless_compose_file.stat.exists
    tags:
    - paperless_ngx
    - docker
  - name: Remove paperless_ngx directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "/opt/paperless_ngx/"
    - "{{ paperless_ngx_config_directory }}"
    # - "{{ paperless_ngx_files_directory }}"
    - "{{ paperless_ngx_postgres_directory }}"
    - "{{ paperless_ngx_data_directory }}"
    - "{{ paperless_ngx_export_directory }}"
  when: not paperless_ngx_enabled
  tags:
  - paperless_ngx
  - docker
