---
- name: Include variables
  include_vars:
    file: vars/main.yml
    name: paperless_ngx_volumes

- name: Deploy paperless-ngx with docker-compose
  block:
  - name: Create paperless_ngx directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ paperless_ngx_config_directory }}"
    - "{{ paperless_ngx_files_directory }}"
    - "{{ paperless_ngx_postgres_directory }}"
    - "{{ paperless_ngx_data_directory }}"
    - "{{ paperless_ngx_export_directory }}"
    - "{{ paperless_ngx_media_directory }}"
    - "{{ paperless_ngx_consume_directory }}"
    - /opt/paperless_ngx/

- name: Deploy Paperless_NGX Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/paperless_ngx/docker-compose.yml
  tags:
  - paperless_ngx
  - docker

- name: Start Paperless_NGX container
  community.docker.docker_compose_v2:
    project_src: /opt/paperless_ngx/
    state: present
  tags:
  - bpaperless_ngx
  - docker

  when: paperless_ngx_enabled

- name: Remove paperless_ngx
  block:
  - name: Stop Paperless_NGX container
    community.docker.docker_compose_v2:
      project_src: /opt/paperless_ngx/
      state: absent
    tags:
    - paperless_ngx
    - docker
  - name: Remove paperless_ngx directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "{{ paperless_ngx_config_directory }}"
    - "{{ paperless_ngx_files_directory }}"
    - "{{ paperless_ngx_postgres_directory }}"
    - "{{ paperless_ngx_data_directory }}"
    - "{{ paperless_ngx_export_directory }}"
    - "{{ paperless_ngx_media_directory }}"
    - "{{ paperless_ngx_consume_directory }}"
    - /opt/paperless_ngx/
  when: not paperless_ngx_enabled
