- name: DEPLOY NZBGet
  block:
  - name: Create NZBget Data Directory
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ nzbget_data_directory }}"


  - name: NZBGet
    community.docker.docker_container:
      name: "{{ nzbget_container_name }}"
      image: "{{ nzbget_image_name }}:{{ nzbget_image_version }}"
      pull: true
      volumes:
      - "{{ nzbget_data_directory }}:/config:rw"
      - "{{ nzbget_download_directory }}:/downloads"
      ports:
      - "{{ nzbget_port }}:6789"
      env:
        TZ: "{{ ansible_nas_timezone }}"
        PUID: "{{ nzbget_user_id }}"
        PGID: "{{ nzbget_group_id }}"
        NZBGET_USER: "{{ nzbget_user }}"
        NZBGET_PASS: "{{ nzbget_pass }}"
      restart_policy: unless-stopped
      memory: "{{ nzbget_memory }}"
      networks:
        - name: "{{ docker_network }}"
      labels:
        traefik.enable: "{{ nzbget_available_externally | string }}"
        traefik.http.routers.nzbget.rule: "Host(`{{ nzbget_hostname }}.{{ ansible_nas_domain }}`)"
        traefik.http.routers.nzbget.tls.certresolver: "letsencrypt"
        traefik.http.routers.nzbget.tls.domains[0].main: "{{ ansible_nas_domain }}"
        traefik.http.routers.nzbget.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
        traefik.http.services.nzbget.loadbalancer.server.port: "6789"
        homepage.group: "Download Tools"
        homepage.name: "NZBGet"
        homepage.icon: sh-nzbget
        homepage.href: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nzbget_port }}"

  # - name: Restart NZBGet if config changed
  #   community.docker.docker_container:
  #     name: "{{ nzbget_container_name }}"
  #     state: started
  #     restart: true
  #   when: nzbget_config_control_ip.changed or nzbget_config_dest_dir.changed or nzbget_config_temp_dir.changed
  when: nzbget_enabled is true

- name: REMOVE NZBGet
  block:
  - name: Stop NZBGet
    community.docker.docker_container:
      name: "{{ nzbget_container_name }}"
      state: absent

  - name: Remove NZBGet Data Directory
    ansible.builtin.file:
      path: "{{ nzbget_data_directory }}"
      state: absent
  when: nzbget_enabled is false
