---
# enable or disable the application
homepage_enabled: false
homepage_available_externally: false

# directories
homepage_data_directory: "{{ docker_home }}/homepage"

# network
homepage_hostname: "homepage"
homepage_port: "11111"

# docker
homepage_container_name: "homepage"
homepage_image_name: "ghcr.io/gethomepage/homepage"
homepage_image_tag: "latest"

# specs
homepage_memory: "1g"

# settings
homepage_title: "{{ ansible_nas_hostname }} Homepage"
homepage_locale: en-GB

# Homepage config files - the variables below are formatted to Homepage YAML config files
homepage_settings_yaml:
  title: "{{ homepage_title }}"
  language: "{{ homepage_locale }}"
  showStats: true

#? Icos:
#? - https://gethomepage.dev/configs/services/#icons
#? - https://selfh.st/icons/

homepage_services_yaml:

- Automation:
  - N8N:
      icon: sh-n8n
      href: "https://{{ n8n_hostname }}.{{ ansible_nas_domain }}/"
      description: n8n on HUS
  - Kestra:
      icon: sh-kestra
      href: "https://{{ kestra_hostname }}.{{ ansible_nas_domain }}/"
      description: Kestra on HUS

- Monitoring:
  - Beszel:
      icon: sh-beszel
      href: http://10.0.40.21:8090/
      description: Beszel Hub on HUS
  - (Utilty Server) Portainer:
      icon: sh-portainer
      href: http://10.0.40.21:19000/
      description: Portainer for HUS

- Productivity:
  - Paperless-NGX:
      icon: sh-paperless-ngx
      href: http://10.0.40.21:8000/
      description: Paperless NGX on HUS

- LAN:
  - UNIFI Router:
      icon: sh-ubiquiti-unifi
      href: http://192.168.1.1/
      description: Unifi Router
  - QNAP:
      icon: sh-qnap
      href: http://10.0.40.2:8080/cgi-bin/
      description: QNAP NAS

homepage_widgets_yaml:
- search:
    provider: google # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    target: _blank # One of _self, _blank, _parent or _top
- greeting:
    text_size: xl
    text: "{{ ansible_nas_hostname }}"
- resources:
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    units: metric # only used by cpu temp
    refresh: 60000 # optional, in ms

homepage_bookmarks_yaml:
- Developer:
  - "Ansible-NAS":
    - abbr: AN
      href: https://ansible-nas.io/
  - Github:
    - abbr: GH
      href: https://github.com/
      icon: github
  - "Hacker News":
    - abbr: HN
      href: https://news.ycombinator.com/
- Social:
  - Reddit:
    - abbr: RE
      href: https://reddit.com/
      icon: reddit
- Entertainment:
  - YouTube:
    - abbr: YT
      href: https://youtube.com/
      icon: youtube
