- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  register: result
  until: result is succeeded

- block:
  - name: Remove docker-py python module
    ansible.builtin.pip:
      name: docker-py
      state: absent
    register: result
    until: result is succeeded

  - name: Install docker python module
    ansible.builtin.pip:
      name: docker
      state: present
    register: result
    until: result is succeeded
  when: ansible_distribution_version is version('24.04', '<')

- name: Install python3-docker package
  ansible.builtin.apt:
    name: python3-docker
    state: present
  register: result
  until: result is succeeded
  when: ansible_distribution_version is version('24.04', '>=')

- name: Create Docker home directory
  ansible.builtin.file:
    path: "{{ docker_home }}"
    mode: 755
    state: directory

- name: Add user account to Docker group
  ansible.builtin.user:
    name: "{{ ansible_nas_user }}"
    groups: docker
    append: yes

- name: Generate Docker daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_json | to_nice_json }}"
  register: docker_config

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
  when: docker_config.changed

- name: Create ansible-docker network
  community.docker.docker_network:
    name: ansible-docker
    state: present
